name: msacco
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  dotted_box: ^0.0.3
  local_auth: ^2.3.0
  provider: ^6.1.2
  loading_animation_widget: ^1.3.0
  logger: ^2.4.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  image_path: "assets/images/launcher_icon.png"
  image_path_android: "assets/images/launcher_icon.png"
  image_path_ios: "assets/images/launcher_icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "#0f4124" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/launcher_icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/images/launcher_icon.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#0f4124"

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/logo.png
    - assets/images/profile_picture.png
    - assets/images/launcher_icon.png
